[package]
name = "near-jsonrpc-adversarial-primitives"
version = "0.2.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
publish = false
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
near-primitives = { path = "../../core/primitives" }
near-jsonrpc-primitives = { path = "../jsonrpc-primitives", features = ["adversarial"] }
near-network = { path = "../network", features = ["adversarial"] }
